### ISSUE TITLE
Upgrade from 2.0 to 2.1 is not straight forward

### ISSUE THREAD

**Issue by thiner** [Tim-Erwin/oauth2-pkce#3]
My application was broken after upgraded from 2.0 to 2.1. The root cause is the `oneTimeParams`. There is not default value for this argument, it fails getTokens request. I have to modify my code from `getTokens()` to `getTokens({})`.

**Comment by Archelyst** [comment]
It is not required, though. I'll have a look into it, if it is required somewhere down the road.

**Comment by maximevw** [comment]
I confirm, I got the same issue.
The problem is in the following method: https://github.com/Tim-Erwin/oauth2-pkce/blob/414ca9ad79db34dad207a8d34ff476e0cf3bfb9c/index.ts#L354 when the function `objectToQueryString` is called:
https://github.com/Tim-Erwin/oauth2-pkce/blob/414ca9ad79db34dad207a8d34ff476e0cf3bfb9c/index.ts#L371

The code should probably be modified with something like that:
```ts
const body = 'grant_type=authorization_code&'
            + ...
            + `code_verifier=${codeVerifier}`
            + (oneTimeParams) ? ('&' + objectToQueryString(oneTimeParams)) : '';
```

**Comment by Archelyst** [comment]
I released a new fixed version. Thanks for reporting this and even providing a fix!
